### web
server:
  port: 8082

### datasource-pool
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rainc_job_test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000


  ### jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.qq.com
    port: 25
    username: 1123015515@qq.com
    password: buvgjlcotupbgiab
    properties:
      mail:
        stmp:
          auth: true
          starttls.enable: true
          starttls.required: true
          socketFactory.class: javax.net.ssl.SSLSocketFactory



rainc:
  job:
    admin:
      trigger-pool-fast-max: 200
      trigger-pool-slow-max: 100
      jwt:
        expire: 604800
        secret: f4e2e52034348f86b67cde581c0f9eb5
      access-token: aaaa
#logging:
logging:
  level:
    root: info
#    org:
#      hibernate:
#        SQL: debug   #debug时显示sql
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace  #trace时，显示参数
