### web
server:
  port: 8081
  servlet:
    context-path: /rainc-job-admin

### datasource-pool
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rainc_job_test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000

  ### jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#logging:
rainc:
  job:
    trigger-pool-fast-max: 200
    trigger-pool-slow-max: 100
#  level: info